[package]
authors = ["RSS Blue", "Dovydas Joksas"]
categories = ["encoding"]
edition = "2021"
keywords = ["podcast", "rss", "xml"]
license = "MIT OR Apache-2.0"
name = "goodpod"
readme = "README.md"
repository = "https://github.com/rssblue/goodpod"
version = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.4.0"

[lib]
doctest = false
